export const INSURANCE_LIST_FIRST_REQUEST = 'INSURANCE_LIST::INSURANCE_LIST_FIRST_REQUEST';
export const INSURANCE_LIST_FIRST_SUCCESS = 'INSURANCE_LIST::INSURANCE_LIST_FIRST_SUCCESS';
export const INSURANCE_LIST_FIRST_ERROR = 'INSURANCE_LIST::INSURANCE_LIST_FIRST_ERROR';

export const INSURANCE_LIST_NEXT_REQUEST = 'INSURANCE_LIST::INSURANCE_LIST_NEXT_REQUEST';
export const INSURANCE_LIST_NEXT_SUCCESS = 'INSURANCE_LIST::INSURANCE_LIST_NEXT_SUCCESS';
export const INSURANCE_LIST_NEXT_ERROR = 'INSURANCE_LIST::INSURANCE_LIST_NEXT_ERROR';

export const INSURANCE_LIST_BACKGROUND_REQUEST = 'INSURANCE_LIST::INSURANCE_LIST_BACKGROUND_REQUEST';
export const INSURANCE_LIST_BACKGROUND_SUCCESS = 'INSURANCE_LIST::INSURANCE_LIST_BACKGROUND_SUCCESS';
export const INSURANCE_LIST_BACKGROUND_ERROR = 'INSURANCE_LIST::INSURANCE_LIST_BACKGROUND_ERROR';

export const DOWNLOAD_INSURANCE_REQUEST = 'INSURANCE_LIST::DOWNLOAD_INSURANCE_REQUEST';
export const DOWNLOAD_INSURANCE_SUCCESS = 'INSURANCE_LIST::DOWNLOAD_INSURANCE_SUCCESS';
export const DOWNLOAD_INSURANCE_ERROR = 'INSURANCE_LIST::DOWNLOAD_INSURANCE_ERROR';

export const SET_FILTER = 'INSURANCE_LIST::SET_FILTER';

//режим отображения компоненты
export const modesList = {
  loadingFirst: 'loadingFirst',
  errorFirst: 'errorFirst',

  loadingNext: 'loadingNext',
  errorNext: 'errorNext',

  loadingBackground: 'loadingBackground',
  errorBackground: 'errorBackground',

  //показываем список полисов
  show: 'show',
};